---
- name: Get openvpn access server installer (Debian)
  get_url:
    url: "{{ openvpn_as_deb_url }}{{ openvpn_as_deb_package }}"
    dest: /tmp
  register: get_openvpn_as

- debug:
    msg: "{{ openvpn_as_deb_package }} was downloaded"
  when: get_openvpn_as|changed

- name: Check if openvpn access server is installed
  command: dpkg-query -W openvpn-as
  register: check_deb
  failed_when: check_deb.rc > 1
  changed_when: check_deb.rc == 1

- name: Install openvpn access server (Debian)
  shell: dpkg -i "/tmp/{{ openvpn_as_deb_package }}"
  sudo: true
  when:  check_deb.rc == 1

- name: Install dependencies (Debian)
  apt: name={{item}}
  with_items: [libpam-pwdfile, python-passlib, expect]
