---

- include_vars: "{{ansible_distribution}}.{{ansible_distribution_release}}.yml"

- include: install_as.deb.yml
  when: ansible_os_family == 'Debian'

- include: install_as.yum.yml
  when: ansible_os_family == 'RedHat'

- include: configure_as.yml

- name: Ensure OpenVPNAS is started
  service: name=openvpnas pattern=/var/run/openvpnas.pid state=started enabled=yes
